# Arista Platform modules for ARM64

ARISTA_PLATFORM_MODULE_VERSION = 1.0

export ARISTA_PLATFORM_MODULE_VERSION

# Get list of Arista platforms (if any arm64 platforms exist)
ARISTA_PLATFORMS_ARM64 = $(subst device/arista/,, $(wildcard device/arista/arm64-arista_*))

export ARISTA_PLATFORMS_ARM64

# All-in-one package (whl + fs + postinst)
ARISTA_PLATFORM_MODULE_ALL = sonic-platform-arista-all_$(ARISTA_PLATFORM_MODULE_VERSION)_arm64.deb
$(ARISTA_PLATFORM_MODULE_ALL)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-arista
$(ARISTA_PLATFORM_MODULE_ALL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ARISTA_PLATFORM_MODULE_ALL)_BUILD_ENV = KVERSION_SHORT=$(KVERSION_SHORT) KVERSION=$(KVERSION) ARCH=$(CONFIGURED_ARCH)
ifneq ($(ARISTA_PLATFORMS_ARM64),)
$(ARISTA_PLATFORM_MODULE_ALL)_PLATFORM = $(ARISTA_PLATFORMS_ARM64)
endif
SONIC_DPKG_DEBS += $(ARISTA_PLATFORM_MODULE_ALL)

export ARISTA_PLATFORM_MODULE_ALL
