# sonic-bmcctld (SONiC BMC control daemon) Debian package

# SONIC_BMCCTLD_PY3 package

SONIC_BMCCTLD_PY3 = sonic_bmcctld-1.0-py3-none-any.whl
$(SONIC_BMCCTLD_PY3)_SRC_PATH = $(SRC_PATH)/sonic-platform-daemons/sonic-bmcctld
$(SONIC_BMCCTLD_PY3)_DEPENDS = $(SONIC_PY_COMMON_PY3) $(SONIC_PLATFORM_COMMON_PY3)
$(SONIC_BMCCTLD_PY3)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(SONIC_BMCCTLD_PY3)_PYTHON_VERSION = 3
SONIC_PYTHON_WHEELS += $(SONIC_BMCCTLD_PY3)
